### ISSUE TITLE
losing attributes when extending model

### ISSUE THREAD

**Issue by amelon** [jupiterjs/jquerymx#41] opened 2011-06-12 10:24 UTC
Extending model return Class with empty attributes.

``` javascript
$.Model.extend('X', {
    attributes: {
        x: 'string',
        v: 'date'
    }
},
{
});

X.extend('Y');
var x = new X(),
     y = new Y();
console.log(x.Class.attributes, y.Class.attributes);

//x.Class.attributes => {x: 'string', v: 'date'}
//y.Class.attributes => {}
```

**Comment by jupiterjs** [comment] 2011-06-12 22:53
This is by design.  Some people wanted it, others not.  Closing b/c it's not a bug.  But, it IS something to consider for the next release.  Maybe make it a milestone?

**Closed as completed by jupiterjs** 2011-06-12 22:53 UTC

**Comment by LazyDev2k** [comment] 2011-08-23 19:10
I think this is a bug. 
Let's assume we have some converters in class X. And we have NO changes in class Y. It just inherited from X. In terms of classic OOP this means that X and Y must behave exactly in same way. However in our case X and Y will differently convert values of properties.
